#!/usr/bin/env python3
"""
Coturn Setup Script for IsaacLab Teleoperation System

This script configures the Coturn TURN server by generating configuration files
based on the user's IP address, username, and password.
"""

import sys
import argparse
import socket
import re
from pathlib import Path


def get_local_ip():
    """Get the local IP address of the machine."""
    try:
        # Connect to a remote address to determine the local IP
        with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as s:
            s.connect(("8.8.8.8", 80))
            return s.getsockname()[0]
    except Exception:
        return "127.0.0.1"


def validate_ip(ip_address):
    """Validate if the provided string is a valid IP address."""
    pattern = r'^(\d{1,3}\.){3}\d{1,3}$'
    if re.match(pattern, ip_address):
        parts = ip_address.split('.')
        return all(0 <= int(part) <= 255 for part in parts)
    return False


def generate_coturn_config(ip_address, username, password):
    """Generate the Coturn configuration file."""

    config_content = f"""# Coturn TURN SERVER configuration file
# Auto-generated by setup_coturn.py

listening-port=3478
tls-listening-port=5349
listening-ip=0.0.0.0
relay-ip={ip_address}
external-ip={ip_address}
min-port=49152
max-port=65535
verbose
fingerprint
lt-cred-mech
user={username}:{password}
realm={ip_address}
log-file=/var/log/turnserver/turnserver.log
simple-log
"""

    output_path = Path(__file__).parent / "custom.conf"
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with open(output_path, 'w') as f:
        f.write(config_content)

    print(f"✓ Generated Coturn configuration: {output_path}")
    return output_path


def main():
    parser = argparse.ArgumentParser(
        description="Setup Coturn TURN server configuration for IsaacLab Teleoperation System",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python setup_coturn.py --domain 192.168.1.100 --username myuser --password mypass
  python setup_coturn.py --auto-detect --username turnuser
  python setup_coturn.py --domain 10.0.0.50 --username user --password pass
        """
    )

    ip_group = parser.add_mutually_exclusive_group(required=True)
    ip_group.add_argument(
        '--domain',
        type=str,
        help='IP address of the TURN server (e.g., 192.168.1.100)'
    )
    ip_group.add_argument(
        '--auto-detect',
        action='store_true',
        help='Automatically detect the local IP address'
    )

    parser.add_argument(
        '--username',
        type=str,
        required=True,
        help='Username for TURN server authentication'
    )

    parser.add_argument(
        '--password',
        type=str,
        required=True,
        help='Password for TURN server authentication (will prompt if not provided)'
    )

    args = parser.parse_args()

    # Determine IP address
    if args.auto_detect:
        ip_address = get_local_ip()
        print(f"Auto-detected IP address: {ip_address}")
    else:
        ip_address = args.ip
        if not validate_ip(ip_address):
            print(f"Error: Invalid IP address format: {ip_address}")
            sys.exit(1)

    print(f"\n🚀 Setting up Coturn TURN server configuration")
    print()

    try:
        # Generate configuration files
        generate_coturn_config(
            ip_address,
            args.username,
            args.password,
        )

        print(f"\n✅ Coturn setup completed successfully!")

    except Exception as e:
        print(f"\n❌ Error during setup: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
